#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=T
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=00:05:00
#SBATCH --mem=64000M
#SBATCH --output=STAMP_Tests_%A.out

# module purge
# module load 2021
# module load Anaconda3/2021.05


# source activate rs

NAME='STAMP_Tests'

# disable wandb
export WANDB_MODE=disabled

# python ./T-DiffRec/main.py --data_path ./datasets/ --dataset=ml-1m_clean --cuda --gpu=0 --run_name=$NAME

python -c "import torch; print(torch.cuda.is_available())"

source deactivate
